name: 🚀 Feature Request
description: Suggest a new feature or enhancement for AI-Hack
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! We love hearing ideas from the community.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: Explain the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative approaches you've considered?
      placeholder: Describe alternative solutions...

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - CLI/Commands
        - AI Model Integration
        - Privacy/Security
        - Performance
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Specific examples of when/how you'd use this feature
      placeholder: |
        Example scenarios:
        1. When working on...
        2. During code review...
        3. For team collaboration...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with AI-Hack's privacy-first philosophy
          required: true
        - label: I'm willing to help implement or test this feature
          required: false
